/** Generated by YAKINDU Statechart Tools code generator. */
package com.yakindu.core;

/**
 * Defines methods to set and unset timers for a state machine's timed event triggers.
 * 
 */
public interface ITimerService {

	/**
	 * Starts the timing for a given time event id.
	 * 
	 * @param callback		an ITimed object that is called when the timer expires
	 * @param eventID		the id of the state machine's time event
	 * @param time			time in milliseconds after which the time event should be triggered
	 * @param isPeriodic	set to true to trigger the time event periodically
	 */
	public void setTimer(ITimed callback, int eventID, long time, boolean isPeriodic);

	/**
	 * Unsets a time event.
	 * 
	 * @param callback	an ITimed object that is called when the timer expires
	 * @param eventID	the id of the state machine's time event
	 */
	public void unsetTimer(ITimed callback, int eventID);
}
