/* Generated by itemis CREATE code generator. */

#ifndef TRAFFICLIGHTSTATEMACHINE_H_
#define TRAFFICLIGHTSTATEMACHINE_H_

/*! Forward declaration of TrafficLightStateMachine, so that cyclically including units can name it. */
class TrafficLightStateMachine;

#include "sc_types.h"
#include "sc_statemachine.h"
#include "sc_eventdriven.h"
#include <deque>
#include <memory>
#include "sc_timer.h"
#include "sc_rxcpp.h"
#include <QObject>

class TrafficLightStateMachine : public QObject, public sc::EventDrivenInterface, public sc::timer::TimedInterface, public std::enable_shared_from_this<sc::timer::TimedInterface> {
	Q_OBJECT
public:
	/*! Enumeration of all states. */
	enum class State
	{
		NO_STATE,
		trafficlight_operating,
		trafficlight_operating_r_prepare,
		trafficlight_operating_r_prepare_switch_to_go,
		trafficlight_operating_r_prepare_switch_to_stop,
		trafficlight_operating_r_stop,
		trafficlight_operating_r_go,
		trafficlight_standby,
		trafficlight_standby_blink_on,
		trafficlight_standby_blink_off
	};
	virtual ~TrafficLightStateMachine();
	/*! The number of states. */
	static constexpr const sc::integer numStates = 9;
	static constexpr const sc::integer scvi_TrafficLightStateMachine_trafficlight_operating = 0;
	static constexpr const sc::integer scvi_TrafficLightStateMachine_trafficlight_operating_r_prepare = 0;
	static constexpr const sc::integer scvi_TrafficLightStateMachine_trafficlight_operating_r_prepare_switch_to_go = 0;
	static constexpr const sc::integer scvi_TrafficLightStateMachine_trafficlight_operating_r_prepare_switch_to_stop = 0;
	static constexpr const sc::integer scvi_TrafficLightStateMachine_trafficlight_operating_r_stop = 0;
	static constexpr const sc::integer scvi_TrafficLightStateMachine_trafficlight_operating_r_go = 0;
	static constexpr const sc::integer scvi_TrafficLightStateMachine_trafficlight_standby = 0;
	static constexpr const sc::integer scvi_TrafficLightStateMachine_trafficlight_standby_blink_on = 0;
	static constexpr const sc::integer scvi_TrafficLightStateMachine_trafficlight_standby_blink_off = 0;
	/*! Enumeration of all events which are consumed. */
	enum class Event
	{
		NO_EVENT,
		standby,
		operate,
		_te0_TrafficLightStateMachine_trafficlight_operating_r_prepare_switch_to_go_,
		_te1_TrafficLightStateMachine_trafficlight_operating_r_prepare_switch_to_stop_,
		_te2_TrafficLightStateMachine_trafficlight_operating_r_stop_,
		_te3_TrafficLightStateMachine_trafficlight_operating_r_go_,
		_te4_TrafficLightStateMachine_trafficlight_standby_blink_on_,
		_te5_TrafficLightStateMachine_trafficlight_standby_blink_off_
	};
	class EventInstance
	{
		public:
			explicit EventInstance(Event id) noexcept : eventId(id){}
			virtual ~EventInstance() = default;
			const Event eventId;
	};
	/*! Get observable for event 'redOn' of default interface scope. */
	sc::rx::Observable<void>& getRedOn() noexcept;
	/*! Get observable for event 'redOff' of default interface scope. */
	sc::rx::Observable<void>& getRedOff() noexcept;
	/*! Get observable for event 'yellowOn' of default interface scope. */
	sc::rx::Observable<void>& getYellowOn() noexcept;
	/*! Get observable for event 'yellowOff' of default interface scope. */
	sc::rx::Observable<void>& getYellowOff() noexcept;
	/*! Get observable for event 'greenOn' of default interface scope. */
	sc::rx::Observable<void>& getGreenOn() noexcept;
	/*! Get observable for event 'greenOff' of default interface scope. */
	sc::rx::Observable<void>& getGreenOff() noexcept;
	void setTimerService(std::shared_ptr<sc::timer::TimerServiceInterface> timerService_) noexcept override;
	std::shared_ptr<sc::timer::TimerServiceInterface> getTimerService() noexcept override;
	sc::integer getNumberOfParallelTimeEvents() noexcept override;
	void raiseTimeEvent(sc::eventid event) override;
	/*! A state machine is active if it has been entered. It is inactive if it has not been entered at all or if it has been exited. */
	bool isActive() const noexcept override;
	/*! Checks whether all active states are final. If there are no active states then the state machine is considered being inactive. */
	bool isFinal() const noexcept override;
	/*! Checks if all members of the state machine that must be set have been set - an operation
	callback, for example.
	 */
	bool check() const noexcept;
	/*! Returns true if the given state is currently active otherwise false. */
	bool isStateActive(TrafficLightStateMachine::State state) const noexcept;
	/*! Can be used by the client code to trigger a run to completion step without raising an event. */
	void triggerWithoutEvent() override;
	void enter() override;
	void exit() override;
	explicit TrafficLightStateMachine(QObject* parent) noexcept;
public slots:
	void standby();
	void operate();
signals:
	/*! Signal representing the out event 'redOn' of default interface scope. */
	void redOn();
	/*! Signal representing the out event 'redOff' of default interface scope. */
	void redOff();
	/*! Signal representing the out event 'yellowOn' of default interface scope. */
	void yellowOn();
	/*! Signal representing the out event 'yellowOff' of default interface scope. */
	void yellowOff();
	/*! Signal representing the out event 'greenOn' of default interface scope. */
	void greenOn();
	/*! Signal representing the out event 'greenOff' of default interface scope. */
	void greenOff();
protected:
	std::deque<std::unique_ptr<TrafficLightStateMachine::EventInstance>> incomingEventQueue {};
	std::unique_ptr<TrafficLightStateMachine::EventInstance> getNextEvent() noexcept;
	bool dispatchEvent(std::unique_ptr<TrafficLightStateMachine::EventInstance> event) noexcept;
private:
	/*! Observable for event 'redOn' of default interface scope. */
	sc::rx::Observable<void> redOnObservable {};
	void raiseRedOn();
	/*! Observable for event 'redOff' of default interface scope. */
	sc::rx::Observable<void> redOffObservable {};
	void raiseRedOff();
	/*! Observable for event 'yellowOn' of default interface scope. */
	sc::rx::Observable<void> yellowOnObservable {};
	void raiseYellowOn();
	/*! Observable for event 'yellowOff' of default interface scope. */
	sc::rx::Observable<void> yellowOffObservable {};
	void raiseYellowOff();
	/*! Observable for event 'greenOn' of default interface scope. */
	sc::rx::Observable<void> greenOnObservable {};
	void raiseGreenOn();
	/*! Observable for event 'greenOff' of default interface scope. */
	sc::rx::Observable<void> greenOffObservable {};
	void raiseGreenOff();
	/*! Indicates event 'standby' of default interface scope is active. */
	bool standbyRaised = false;
	/*! Indicates event 'operate' of default interface scope is active. */
	bool operateRaised = false;
	/*! Indicates event 'TrafficLightStateMachine_trafficlight_operating_r_prepare_switch_to_go_time_event_0' of scope is active. */
	bool TrafficLightStateMachine_trafficlight_operating_r_prepare_switch_to_go_time_event_0Raised = false;
	/*! Indicates event 'TrafficLightStateMachine_trafficlight_operating_r_prepare_switch_to_stop_time_event_0' of scope is active. */
	bool TrafficLightStateMachine_trafficlight_operating_r_prepare_switch_to_stop_time_event_0Raised = false;
	/*! Indicates event 'TrafficLightStateMachine_trafficlight_operating_r_stop_time_event_0' of scope is active. */
	bool TrafficLightStateMachine_trafficlight_operating_r_stop_time_event_0Raised = false;
	/*! Indicates event 'TrafficLightStateMachine_trafficlight_operating_r_go_time_event_0' of scope is active. */
	bool TrafficLightStateMachine_trafficlight_operating_r_go_time_event_0Raised = false;
	/*! Indicates event 'TrafficLightStateMachine_trafficlight_standby_blink_on_time_event_0' of scope is active. */
	bool TrafficLightStateMachine_trafficlight_standby_blink_on_time_event_0Raised = false;
	/*! Indicates event 'TrafficLightStateMachine_trafficlight_standby_blink_off_time_event_0' of scope is active. */
	bool TrafficLightStateMachine_trafficlight_standby_blink_off_time_event_0Raised = false;
	std::shared_ptr<sc::timer::TimerServiceInterface> timerService = nullptr;
	bool isExecuting = false;
	/*! the maximum number of orthogonal states defines the dimension of the state configuration vector. */
	static constexpr const sc::ushort maxOrthogonalStates = 1;
	TrafficLightStateMachine::State stateConfVector[maxOrthogonalStates] {};
	/*! Discards the incoming events of the step that just finished, so that the next step sees only events raised since. */
	void clearInEvents() noexcept;
	sc::integer trafficlight_operating_react(const sc::integer transitioned_before);
	sc::integer trafficlight_operating_r_prepare_react(const sc::integer transitioned_before);
	sc::integer trafficlight_operating_r_prepare_switch_to_go_react(const sc::integer transitioned_before);
	sc::integer trafficlight_operating_r_prepare_switch_to_stop_react(const sc::integer transitioned_before);
	sc::integer trafficlight_operating_r_stop_react(const sc::integer transitioned_before);
	sc::integer trafficlight_operating_r_go_react(const sc::integer transitioned_before);
	sc::integer trafficlight_standby_react(const sc::integer transitioned_before);
	sc::integer trafficlight_standby_blink_on_react(const sc::integer transitioned_before);
	sc::integer trafficlight_standby_blink_off_react(const sc::integer transitioned_before);
	void microStep();
	void runCycle();
	TrafficLightStateMachine(const TrafficLightStateMachine& rhs);
	TrafficLightStateMachine& operator=(const TrafficLightStateMachine& rhs);
};

#endif /* TRAFFICLIGHTSTATEMACHINE_H_ */

