/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef BLINKMETA_H_
#define BLINKMETA_H_

#include "base/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string BlinkMeta_feature_names[];

extern sc_string BlinkMeta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* BLINKMETA_H_ */
