/** Generated by YAKINDU Statechart Tools code generator. */


#include "base\sc_types.h"
#include "base\sc_tracing.h"

#include "Blink.h"
#include "BlinkRequired.h"

/*! \file Implementation of the state machine 'blink'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enact_raspberry_pi_Blink_blinky_On(Blink* handle);
static void enact_raspberry_pi_Blink_blinky_Off(Blink* handle);
static void exact_raspberry_pi_Blink_blinky_On(Blink* handle);
static void exact_raspberry_pi_Blink_blinky_Off(Blink* handle);
static void enseq_raspberry_pi_Blink_default(Blink* handle);
static void enseq_raspberry_pi_Blink_blinky_On_default(Blink* handle);
static void enseq_raspberry_pi_Blink_blinky_Off_default(Blink* handle);
static void enseq_raspberry_pi_Idle_default(Blink* handle);
static void enseq_raspberry_pi_default(Blink* handle);
static void enseq_raspberry_pi_Blink_blinky_default(Blink* handle);
static void exseq_raspberry_pi_Blink(Blink* handle);
static void exseq_raspberry_pi_Blink_blinky_On(Blink* handle);
static void exseq_raspberry_pi_Blink_blinky_Off(Blink* handle);
static void exseq_raspberry_pi_Idle(Blink* handle);
static void exseq_raspberry_pi(Blink* handle);
static void exseq_raspberry_pi_Blink_blinky(Blink* handle);
static void react_raspberry_pi_Blink_blinky__entry_Default(Blink* handle);
static void react_raspberry_pi__entry_Default(Blink* handle);

/*! State machine reactions. */
static sc_boolean react(Blink* handle);

/*! The reactions of state Blink. */
static sc_boolean raspberry_pi_Blink_react(Blink* handle, const sc_boolean try_transition);

/*! The reactions of state On. */
static sc_boolean raspberry_pi_Blink_blinky_On_react(Blink* handle, const sc_boolean try_transition);

/*! The reactions of state Off. */
static sc_boolean raspberry_pi_Blink_blinky_Off_react(Blink* handle, const sc_boolean try_transition);

/*! The reactions of state Idle. */
static sc_boolean raspberry_pi_Idle_react(Blink* handle, const sc_boolean try_transition);


static void clearInEvents(Blink* handle);



static void blink_eventqueue_init(blink_eventqueue * eq, blink_event *buffer, sc_integer capacity);
static sc_integer blink_eventqueue_size(blink_eventqueue * eq);
static blink_event blink_eventqueue_pop(blink_eventqueue * eq);
static void blink_event_init(blink_event * ev, blink_event_name name);
static sc_boolean blink_eventqueue_push(blink_eventqueue * eq, blink_event ev);
static void blink_add_event_to_queue(blink_eventqueue * eq, blink_event_name name);
static void blink_dispatch_event(Blink* handle, const blink_event * event);
static blink_event blink_get_next_event(Blink* handle);
static void blink_dispatch_next_event(Blink* handle);


static sc_integer time_event_index(Blink* handle, sc_eventid evid);

static sc_integer time_event_index(Blink* handle, sc_eventid evid)
{
	sc_integer tev_id = ((sc_intptr_t)evid - (sc_intptr_t)&(handle->timeEvents)) / sizeof(sc_boolean);
	return tev_id;
}

void blink_initWithTracing(Blink* handle, sc_trace_handler *trace_handler)
{
	sc_integer i;
	
	for (i = 0; i < BLINK_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Blink_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	
	
	/* Default init sequence for statechart blink */
	handle->internal.low = 0;
	SC_TRACE_FEATURE(handle, sc_trace_variable_set, blinkIface_low, &handle->internal.low);
	handle->internal.high = 1;
	SC_TRACE_FEATURE(handle, sc_trace_variable_set, blinkIface_high, &handle->internal.high);
	handle->internal.output = 1;
	SC_TRACE_FEATURE(handle, sc_trace_variable_set, blinkIface_output, &handle->internal.output);
	handle->internal.led_pin = 0;
	SC_TRACE_FEATURE(handle, sc_trace_variable_set, blinkIface_led_pin, &handle->internal.led_pin);
	handle->iface.delay = 2000;
	SC_TRACE_FEATURE(handle, sc_trace_variable_set, blinkIface_delay, &handle->iface.delay);
	
	handle->isExecuting = bool_false;
	blink_eventqueue_init(&handle->in_event_queue, handle->in_buffer, BLINK_IN_EVENTQUEUE_BUFFERSIZE);
	handle->trace_handler = trace_handler;
}

void blink_init(Blink* handle)
{
	blink_initWithTracing(handle, sc_null);
}

void blink_enter(Blink* handle)
{
	/* Activates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	SC_TRACE(handle, sc_trace_machine_enter);
	/* Default enter sequence for statechart blink */
	/* Entry action for statechart 'blink'. */
	blinkIface_pinMode(handle, handle->internal.led_pin, handle->internal.output);
	enseq_raspberry_pi_default(handle);
	handle->isExecuting = bool_false;
}

void blink_exit(Blink* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	SC_TRACE(handle, sc_trace_machine_exit);
	/* Default exit sequence for statechart blink */
	exseq_raspberry_pi(handle);
	handle->isExecuting = bool_false;
}

void blink_runCycle(Blink* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	SC_TRACE(handle, sc_trace_machine_run_cycle_start);
	blink_dispatch_next_event(handle);
	do
	{ 
		for (handle->stateConfVectorPosition = 0;
			handle->stateConfVectorPosition < BLINK_MAX_ORTHOGONAL_STATES;
			handle->stateConfVectorPosition++)
			{
				
			switch (handle->stateConfVector[handle->stateConfVectorPosition])
			{
			case Blink_raspberry_pi_Blink_blinky_On:
			{
				raspberry_pi_Blink_blinky_On_react(handle, bool_true);
				break;
			}
			case Blink_raspberry_pi_Blink_blinky_Off:
			{
				raspberry_pi_Blink_blinky_Off_react(handle, bool_true);
				break;
			}
			case Blink_raspberry_pi_Idle:
			{
				raspberry_pi_Idle_react(handle, bool_true);
				break;
			}
			default:
				break;
			}
		}
		clearInEvents(handle);
		blink_dispatch_next_event(handle);
	} while (((handle->iface.toggle_raised == bool_true) || (handle->timeEvents.blink_raspberry_pi_Blink_blinky_On_tev0_raised == bool_true)) || (handle->timeEvents.blink_raspberry_pi_Blink_blinky_Off_tev0_raised == bool_true));
	SC_TRACE(handle, sc_trace_machine_run_cycle_end);
	handle->isExecuting = bool_false;
}


sc_boolean blink_isActive(const Blink* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < BLINK_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Blink_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean blink_isFinal(const Blink* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

void blink_raiseTimeEvent(Blink* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(BlinkTimeEvents))
	{
		*(sc_boolean*)evid = bool_true;
		sc_integer tev_id = time_event_index(handle, evid);
		SC_TRACE_TIME_EVENT(handle, sc_trace_time_event_raised, tev_id);
		blink_runCycle(handle);
	}
}

sc_boolean blink_isStateActive(const Blink* handle, BlinkStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Blink_raspberry_pi_Blink :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_RASPBERRY_PI_BLINK] >= Blink_raspberry_pi_Blink
				&& handle->stateConfVector[SCVI_BLINK_RASPBERRY_PI_BLINK] <= Blink_raspberry_pi_Blink_blinky_Off);
			break;
		case Blink_raspberry_pi_Blink_blinky_On :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_RASPBERRY_PI_BLINK_BLINKY_ON] == Blink_raspberry_pi_Blink_blinky_On
			);
			break;
		case Blink_raspberry_pi_Blink_blinky_Off :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_RASPBERRY_PI_BLINK_BLINKY_OFF] == Blink_raspberry_pi_Blink_blinky_Off
			);
			break;
		case Blink_raspberry_pi_Idle :
			result = (sc_boolean) (handle->stateConfVector[SCVI_BLINK_RASPBERRY_PI_IDLE] == Blink_raspberry_pi_Idle
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(Blink* handle)
{
	handle->iface.toggle_raised = bool_false;
	handle->timeEvents.blink_raspberry_pi_Blink_blinky_On_tev0_raised = bool_false;
	handle->timeEvents.blink_raspberry_pi_Blink_blinky_Off_tev0_raised = bool_false;
}


void blinkIface_raise_toggle(Blink* handle)
{
	SC_TRACE_FEATURE(handle, sc_trace_event_raised, blinkIface_toggle, sc_null)
	blink_add_event_to_queue(&(handle->in_event_queue), blinkIface_toggle);
	blink_runCycle(handle);
}



sc_integer blinkIface_get_delay(const Blink* handle)
{
	return handle->iface.delay;
}
void blinkIface_set_delay(Blink* handle, sc_integer value)
{
	SC_TRACE_FEATURE(handle, sc_trace_variable_set, blinkIface_delay, &value);
	handle->iface.delay = value;
}

/* implementations of all internal functions */

/* Entry action for state 'On'. */
static void enact_raspberry_pi_Blink_blinky_On(Blink* handle)
{
	/* Entry action for state 'On'. */
	blink_setTimer(handle, (sc_eventid) &(handle->timeEvents.blink_raspberry_pi_Blink_blinky_On_tev0_raised) , handle->iface.delay, bool_false);
	SC_TRACE_TIME_EVENT(handle, sc_trace_time_event_set, 0);
	blinkIface_digitalWrite(handle, handle->internal.led_pin, handle->internal.high);
}

/* Entry action for state 'Off'. */
static void enact_raspberry_pi_Blink_blinky_Off(Blink* handle)
{
	/* Entry action for state 'Off'. */
	blink_setTimer(handle, (sc_eventid) &(handle->timeEvents.blink_raspberry_pi_Blink_blinky_Off_tev0_raised) , handle->iface.delay, bool_false);
	SC_TRACE_TIME_EVENT(handle, sc_trace_time_event_set, 1);
	blinkIface_digitalWrite(handle, handle->internal.led_pin, handle->internal.low);
}

/* Exit action for state 'On'. */
static void exact_raspberry_pi_Blink_blinky_On(Blink* handle)
{
	/* Exit action for state 'On'. */
	blink_unsetTimer(handle, (sc_eventid) &(handle->timeEvents.blink_raspberry_pi_Blink_blinky_On_tev0_raised) );		
	SC_TRACE_TIME_EVENT(handle, sc_trace_time_event_unset, 0);
}

/* Exit action for state 'Off'. */
static void exact_raspberry_pi_Blink_blinky_Off(Blink* handle)
{
	/* Exit action for state 'Off'. */
	blink_unsetTimer(handle, (sc_eventid) &(handle->timeEvents.blink_raspberry_pi_Blink_blinky_Off_tev0_raised) );		
	SC_TRACE_TIME_EVENT(handle, sc_trace_time_event_unset, 1);
}

/* 'default' enter sequence for state Blink */
static void enseq_raspberry_pi_Blink_default(Blink* handle)
{
	/* 'default' enter sequence for state Blink */
	SC_TRACE_STATE(handle, sc_trace_state_entered, Blink_raspberry_pi_Blink);
	enseq_raspberry_pi_Blink_blinky_default(handle);
}

/* 'default' enter sequence for state On */
static void enseq_raspberry_pi_Blink_blinky_On_default(Blink* handle)
{
	/* 'default' enter sequence for state On */
	enact_raspberry_pi_Blink_blinky_On(handle);
	SC_TRACE_STATE(handle, sc_trace_state_entered, Blink_raspberry_pi_Blink_blinky_On);
	handle->stateConfVector[0] = Blink_raspberry_pi_Blink_blinky_On;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Off */
static void enseq_raspberry_pi_Blink_blinky_Off_default(Blink* handle)
{
	/* 'default' enter sequence for state Off */
	enact_raspberry_pi_Blink_blinky_Off(handle);
	SC_TRACE_STATE(handle, sc_trace_state_entered, Blink_raspberry_pi_Blink_blinky_Off);
	handle->stateConfVector[0] = Blink_raspberry_pi_Blink_blinky_Off;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state Idle */
static void enseq_raspberry_pi_Idle_default(Blink* handle)
{
	/* 'default' enter sequence for state Idle */
	SC_TRACE_STATE(handle, sc_trace_state_entered, Blink_raspberry_pi_Idle);
	handle->stateConfVector[0] = Blink_raspberry_pi_Idle;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region raspberry pi */
static void enseq_raspberry_pi_default(Blink* handle)
{
	/* 'default' enter sequence for region raspberry pi */
	react_raspberry_pi__entry_Default(handle);
}

/* 'default' enter sequence for region blinky */
static void enseq_raspberry_pi_Blink_blinky_default(Blink* handle)
{
	/* 'default' enter sequence for region blinky */
	react_raspberry_pi_Blink_blinky__entry_Default(handle);
}

/* Default exit sequence for state Blink */
static void exseq_raspberry_pi_Blink(Blink* handle)
{
	/* Default exit sequence for state Blink */
	exseq_raspberry_pi_Blink_blinky(handle);
	SC_TRACE_STATE(handle, sc_trace_state_exited, Blink_raspberry_pi_Blink);
}

/* Default exit sequence for state On */
static void exseq_raspberry_pi_Blink_blinky_On(Blink* handle)
{
	/* Default exit sequence for state On */
	handle->stateConfVector[0] = Blink_last_state;
	handle->stateConfVectorPosition = 0;
	exact_raspberry_pi_Blink_blinky_On(handle);
	SC_TRACE_STATE(handle, sc_trace_state_exited, Blink_raspberry_pi_Blink_blinky_On);
}

/* Default exit sequence for state Off */
static void exseq_raspberry_pi_Blink_blinky_Off(Blink* handle)
{
	/* Default exit sequence for state Off */
	handle->stateConfVector[0] = Blink_last_state;
	handle->stateConfVectorPosition = 0;
	exact_raspberry_pi_Blink_blinky_Off(handle);
	SC_TRACE_STATE(handle, sc_trace_state_exited, Blink_raspberry_pi_Blink_blinky_Off);
}

/* Default exit sequence for state Idle */
static void exseq_raspberry_pi_Idle(Blink* handle)
{
	/* Default exit sequence for state Idle */
	handle->stateConfVector[0] = Blink_last_state;
	handle->stateConfVectorPosition = 0;
	SC_TRACE_STATE(handle, sc_trace_state_exited, Blink_raspberry_pi_Idle);
}

/* Default exit sequence for region raspberry pi */
static void exseq_raspberry_pi(Blink* handle)
{
	/* Default exit sequence for region raspberry pi */
	/* Handle exit of all possible states (of blink.raspberry_pi) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Blink_raspberry_pi_Blink_blinky_On :
		{
			exseq_raspberry_pi_Blink_blinky_On(handle);
			SC_TRACE_STATE(handle, sc_trace_state_exited, Blink_raspberry_pi_Blink);
			break;
		}
		case Blink_raspberry_pi_Blink_blinky_Off :
		{
			exseq_raspberry_pi_Blink_blinky_Off(handle);
			SC_TRACE_STATE(handle, sc_trace_state_exited, Blink_raspberry_pi_Blink);
			break;
		}
		case Blink_raspberry_pi_Idle :
		{
			exseq_raspberry_pi_Idle(handle);
			break;
		}
		default: break;
	}
}

/* Default exit sequence for region blinky */
static void exseq_raspberry_pi_Blink_blinky(Blink* handle)
{
	/* Default exit sequence for region blinky */
	/* Handle exit of all possible states (of blink.raspberry_pi.Blink.blinky) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Blink_raspberry_pi_Blink_blinky_On :
		{
			exseq_raspberry_pi_Blink_blinky_On(handle);
			break;
		}
		case Blink_raspberry_pi_Blink_blinky_Off :
		{
			exseq_raspberry_pi_Blink_blinky_Off(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_raspberry_pi_Blink_blinky__entry_Default(Blink* handle)
{
	/* Default react sequence for initial entry  */
	enseq_raspberry_pi_Blink_blinky_Off_default(handle);
}

/* Default react sequence for initial entry  */
static void react_raspberry_pi__entry_Default(Blink* handle)
{
	/* Default react sequence for initial entry  */
	enseq_raspberry_pi_Idle_default(handle);
}


static sc_boolean react(Blink* handle)
{
	/* State machine reactions. */
	SC_UNUSED(handle);
	return bool_false;
}

static sc_boolean raspberry_pi_Blink_react(Blink* handle, const sc_boolean try_transition)
{
	/* The reactions of state Blink. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.toggle_raised == bool_true)
			{ 
				exseq_raspberry_pi_Blink(handle);
				enseq_raspberry_pi_Idle_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}

static sc_boolean raspberry_pi_Blink_blinky_On_react(Blink* handle, const sc_boolean try_transition)
{
	/* The reactions of state On. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((raspberry_pi_Blink_react(handle, try_transition)) == (bool_false))
		{ 
			if (handle->timeEvents.blink_raspberry_pi_Blink_blinky_On_tev0_raised == bool_true)
			{ 
				exseq_raspberry_pi_Blink_blinky_On(handle);
				enseq_raspberry_pi_Blink_blinky_Off_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}

static sc_boolean raspberry_pi_Blink_blinky_Off_react(Blink* handle, const sc_boolean try_transition)
{
	/* The reactions of state Off. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((raspberry_pi_Blink_react(handle, try_transition)) == (bool_false))
		{ 
			if (handle->timeEvents.blink_raspberry_pi_Blink_blinky_Off_tev0_raised == bool_true)
			{ 
				exseq_raspberry_pi_Blink_blinky_Off(handle);
				enseq_raspberry_pi_Blink_blinky_On_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}

static sc_boolean raspberry_pi_Idle_react(Blink* handle, const sc_boolean try_transition)
{
	/* The reactions of state Idle. */
 			sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.toggle_raised == bool_true)
			{ 
				exseq_raspberry_pi_Idle(handle);
				enseq_raspberry_pi_Blink_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} return did_transition;
}




static void blink_eventqueue_init(blink_eventqueue * eq, blink_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer blink_eventqueue_size(blink_eventqueue * eq)
{
	return eq->size;
}

static blink_event blink_eventqueue_pop(blink_eventqueue * eq)
{
	blink_event event;
	if(blink_eventqueue_size(eq) <= 0) {
		blink_event_init(&event, blink_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean blink_eventqueue_push(blink_eventqueue * eq, blink_event ev)
{
	if(blink_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void blink_event_init(blink_event * ev, blink_event_name name)
{
	ev->name = name;
}

static void blink_add_event_to_queue(blink_eventqueue * eq, blink_event_name name)
{
	blink_event event;
	blink_event_init(&event, name);
	blink_eventqueue_push(eq, event);
}

static void blink_dispatch_event(Blink* handle, const blink_event * event) {
	switch(event->name) {
		case blinkIface_toggle:
		{
			handle->iface.toggle_raised = bool_true;
			break;
		}
		default:
			break;
	}
}

static blink_event blink_get_next_event(Blink* handle)
{
	blink_event next_event;
	blink_event_init(&next_event, blink_invalid_event);
	if(blink_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = blink_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static void blink_dispatch_next_event(Blink* handle)
{
	blink_event nextEvent;
	nextEvent = blink_get_next_event(handle);
	blink_dispatch_event(handle, &nextEvent);
}
