/** Generated by YAKINDU Statechart Tools code generator. */

#include "BlinkMeta.h"				
		
sc_string BlinkMeta_feature_names[] = {
	"<nothing>",
	"low",
	"high",
	"output",
	"led_pin",
	"delay",
	"toggle"
};

sc_string BlinkMeta_state_names[] = {
	"<nostate>",
	"raspberry_pi.Blink",
	"raspberry_pi.Blink.blinky.On",
	"raspberry_pi.Blink.blinky.Off",
	"raspberry_pi.Idle"
};
