/** Generated by YAKINDU Statechart Tools code generator. */

#include "StateMachine.h"
#include "../src/sc_types.h"
#include "StateMachineRequired.h"

/*! \file Implementation of the state machine 'StateMachine'
*/

/* prototypes of all internal functions */
static void enact_main_region_StateA(StateMachine* handle);
static void enact_main_region_StateB(StateMachine* handle);
static void exact_main_region_StateB(StateMachine* handle);
static void enseq_main_region_StateA_default(StateMachine* handle);
static void enseq_main_region_StateB_default(StateMachine* handle);
static void enseq_main_region__final__default(StateMachine* handle);
static void enseq_main_region_default(StateMachine* handle);
static void exseq_main_region_StateA(StateMachine* handle);
static void exseq_main_region_StateB(StateMachine* handle);
static void exseq_main_region__final_(StateMachine* handle);
static void exseq_main_region(StateMachine* handle);
static void react_main_region__entry_Default(StateMachine* handle);
static sc_boolean react(StateMachine* handle);
static sc_boolean main_region_StateA_react(StateMachine* handle, const sc_boolean try_transition);
static sc_boolean main_region_StateB_react(StateMachine* handle, const sc_boolean try_transition);
static sc_boolean main_region__final__react(StateMachine* handle, const sc_boolean try_transition);
static void clearInEvents(StateMachine* handle);
static void clearOutEvents(StateMachine* handle);


void stateMachine_init(StateMachine* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATEMACHINE_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = StateMachine_last_state;
	}
	
	
	handle->stateConfVectorPosition = 0;
	
	clearInEvents(handle);
	clearOutEvents(handle);
	
}

void stateMachine_enter(StateMachine* handle)
{
	/* Default enter sequence for statechart StateMachine */
	enseq_main_region_default(handle);
}

void stateMachine_runCycle(StateMachine* handle)
{
	clearOutEvents(handle);
	for (handle->stateConfVectorPosition = 0;
		handle->stateConfVectorPosition < STATEMACHINE_MAX_ORTHOGONAL_STATES;
		handle->stateConfVectorPosition++)
		{
			
		switch (handle->stateConfVector[handle->stateConfVectorPosition])
		{
		case StateMachine_main_region_StateA:
		{
			main_region_StateA_react(handle, bool_true);
			break;
		}
		case StateMachine_main_region_StateB:
		{
			main_region_StateB_react(handle, bool_true);
			break;
		}
		case StateMachine_main_region__final_:
		{
			main_region__final__react(handle, bool_true);
			break;
		}
		default:
			break;
		}
	}
	
	clearInEvents(handle);
}

void stateMachine_exit(StateMachine* handle)
{
	/* Default exit sequence for statechart StateMachine */
	exseq_main_region(handle);
}

sc_boolean stateMachine_isActive(const StateMachine* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATEMACHINE_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != StateMachine_last_state;
	}
	
	return result;
}

sc_boolean stateMachine_isFinal(const StateMachine* handle)
{
	return (handle->stateConfVector[0] == StateMachine_main_region__final_);

}

void stateMachine_raiseTimeEvent(StateMachine* handle, sc_eventid evid)
{
	if ( ((sc_intptr_t)evid) >= ((sc_intptr_t)&(handle->timeEvents))
		&&  ((sc_intptr_t)evid) < ((sc_intptr_t)&(handle->timeEvents)) + (unsigned)sizeof(StateMachineTimeEvents))
		{
		*(sc_boolean*)evid = bool_true;
	}		
}

sc_boolean stateMachine_isStateActive(const StateMachine* handle, StateMachineStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case StateMachine_main_region_StateA :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATEMACHINE_MAIN_REGION_STATEA] == StateMachine_main_region_StateA
			);
			break;
		case StateMachine_main_region_StateB :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATEMACHINE_MAIN_REGION_STATEB] == StateMachine_main_region_StateB
			);
			break;
		case StateMachine_main_region__final_ :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATEMACHINE_MAIN_REGION__FINAL_] == StateMachine_main_region__final_
			);
			break;
		default:
			result = bool_false;
			break;
	}
	return result;
}

static void clearInEvents(StateMachine* handle)
{
	handle->iface.inEvent1_raised = bool_false;
	handle->iface.inEvent2_raised = bool_false;
	handle->timeEvents.stateMachine_main_region_StateB_tev0_raised = bool_false;
}

static void clearOutEvents(StateMachine* handle)
{
	handle->iface.outEvent1_raised = bool_false;
	handle->iface.outEvent2_raised = bool_false;
}

void stateMachineIface_raise_inEvent1(StateMachine* handle)
{
	handle->iface.inEvent1_raised = bool_true;
}
void stateMachineIface_raise_inEvent2(StateMachine* handle)
{
	handle->iface.inEvent2_raised = bool_true;
}

sc_boolean stateMachineIface_israised_outEvent1(const StateMachine* handle)
{
	return handle->iface.outEvent1_raised;
}
sc_boolean stateMachineIface_israised_outEvent2(const StateMachine* handle)
{
	return handle->iface.outEvent2_raised;
}


/* implementations of all internal functions */

/* Entry action for state 'StateA'. */
static void enact_main_region_StateA(StateMachine* handle)
{
	/* Entry action for state 'StateA'. */
	handle->iface.outEvent1_raised = bool_true;
}

/* Entry action for state 'StateB'. */
static void enact_main_region_StateB(StateMachine* handle)
{
	/* Entry action for state 'StateB'. */
	stateMachine_setTimer(handle, (sc_eventid) &(handle->timeEvents.stateMachine_main_region_StateB_tev0_raised) , (10 * 1000), bool_false);
	handle->iface.outEvent2_raised = bool_true;
}

/* Exit action for state 'StateB'. */
static void exact_main_region_StateB(StateMachine* handle)
{
	/* Exit action for state 'StateB'. */
	stateMachine_unsetTimer(handle, (sc_eventid) &(handle->timeEvents.stateMachine_main_region_StateB_tev0_raised) );		
}

/* 'default' enter sequence for state StateA */
static void enseq_main_region_StateA_default(StateMachine* handle)
{
	/* 'default' enter sequence for state StateA */
	enact_main_region_StateA(handle);
	handle->stateConfVector[0] = StateMachine_main_region_StateA;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for state StateB */
static void enseq_main_region_StateB_default(StateMachine* handle)
{
	/* 'default' enter sequence for state StateB */
	enact_main_region_StateB(handle);
	handle->stateConfVector[0] = StateMachine_main_region_StateB;
	handle->stateConfVectorPosition = 0;
}

/* Default enter sequence for state null */
static void enseq_main_region__final__default(StateMachine* handle)
{
	/* Default enter sequence for state null */
	handle->stateConfVector[0] = StateMachine_main_region__final_;
	handle->stateConfVectorPosition = 0;
}

/* 'default' enter sequence for region main region */
static void enseq_main_region_default(StateMachine* handle)
{
	/* 'default' enter sequence for region main region */
	react_main_region__entry_Default(handle);
}

/* Default exit sequence for state StateA */
static void exseq_main_region_StateA(StateMachine* handle)
{
	/* Default exit sequence for state StateA */
	handle->stateConfVector[0] = StateMachine_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for state StateB */
static void exseq_main_region_StateB(StateMachine* handle)
{
	/* Default exit sequence for state StateB */
	handle->stateConfVector[0] = StateMachine_last_state;
	handle->stateConfVectorPosition = 0;
	exact_main_region_StateB(handle);
}

/* Default exit sequence for final state. */
static void exseq_main_region__final_(StateMachine* handle)
{
	/* Default exit sequence for final state. */
	handle->stateConfVector[0] = StateMachine_last_state;
	handle->stateConfVectorPosition = 0;
}

/* Default exit sequence for region main region */
static void exseq_main_region(StateMachine* handle)
{
	/* Default exit sequence for region main region */
	/* Handle exit of all possible states (of StateMachine.main_region) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case StateMachine_main_region_StateA :
		{
			exseq_main_region_StateA(handle);
			break;
		}
		case StateMachine_main_region_StateB :
		{
			exseq_main_region_StateB(handle);
			break;
		}
		case StateMachine_main_region__final_ :
		{
			exseq_main_region__final_(handle);
			break;
		}
		default: break;
	}
}

/* Default react sequence for initial entry  */
static void react_main_region__entry_Default(StateMachine* handle)
{
	/* Default react sequence for initial entry  */
	enseq_main_region_StateA_default(handle);
}

static sc_boolean react(StateMachine* handle) {
	/* State machine reactions. */
	return bool_false;
}

static sc_boolean main_region_StateA_react(StateMachine* handle, const sc_boolean try_transition) {
	/* The reactions of state StateA. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->iface.inEvent1_raised == bool_true)
			{ 
				exseq_main_region_StateA(handle);
				enseq_main_region_StateB_default(handle);
			}  else
			{
				if (handle->iface.inEvent2_raised == bool_true)
				{ 
					exseq_main_region_StateA(handle);
					enseq_main_region__final__default(handle);
				}  else
				{
					did_transition = bool_false;
				}
			}
		} 
	} 
	return did_transition;
}

static sc_boolean main_region_StateB_react(StateMachine* handle, const sc_boolean try_transition) {
	/* The reactions of state StateB. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			if (handle->timeEvents.stateMachine_main_region_StateB_tev0_raised == bool_true)
			{ 
				exseq_main_region_StateB(handle);
				enseq_main_region_StateA_default(handle);
			}  else
			{
				did_transition = bool_false;
			}
		} 
	} 
	return did_transition;
}

static sc_boolean main_region__final__react(StateMachine* handle, const sc_boolean try_transition) {
	/* The reactions of state null. */
	sc_boolean did_transition = try_transition;
	if (try_transition == bool_true)
	{ 
		if ((react(handle)) == (bool_false))
		{ 
			did_transition = bool_false;
		} 
	} 
	return did_transition;
}


