/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef SC_YET_H
#define SC_YET_H

#include "sc_types.h"
#include "sc_rxc.h"

#ifdef __cplusplus
extern "C" {
#endif

#define YET_MESSAGE_INIT_BEGIN '%'
#define YET_MESSAGE_UPDATE_BEGIN '#'
#define YET_MESSAGE_SEPARATOR ','
#define YET_ERR_INVALID_MSG 1
#define YET_ERR_INVALID_BEGIN 2
#define YET_ERR_INVALID_TIMESTAMP 4
#define YET_ERR_INVALID_KEY 8
#define YET_ERR_INVALID_VALUE 16
#define YET_ERR_MISSING_VALUE 32
#define YET_ERR_NULLPTR 64

enum yet_message_type {
	INIT,
	UPDATE
};

typedef struct yet_message yet_message;

struct yet_message {
	enum yet_message_type type;
	unsigned long timestamp;
	char* key;
	char* value;
};


typedef struct yet_scope yet_scope;

/**
 * When a scope is matched, its handler is called.
 * The handler should return 0 on success.
 */
typedef uint8_t (*yet_handler)(yet_scope* scope, yet_message *msg, char *fqn);

struct yet_scope {
	yet_scope *parent_scope;
	yet_scope **child_scopes;
	sc_integer num_child_scopes;
	sc_string name;
	yet_handler handler;
	void* instance;
//	unsigned long (*current_timestamp)();

	sc_observer   message_receiver;
	sc_observable trace_messages;

};


/*
 * Functions that need to be implemented by clients
 */


/*! Function to retrieve the current timestamp, ideally in milliseconds. */
extern unsigned long get_current_timestamp();

/*
 * This function is called by tracing state machines.
 */
extern void yet_scope_send(yet_scope* self, struct yet_message * msg);

/*!
 * If a message was received, call this function to process it.
 */
extern void yet_scope_accept_message(yet_scope *scope, char *text);

extern void yet_scope_dispatch_message(yet_scope* scope, yet_message* msg, char *fqn);

extern char* yet_scope_create_message(yet_scope* scope, char* msg, char* dst, sc_boolean meta);

extern void yet_scope_init(yet_scope* scope, yet_scope* parent_scope, char *name, yet_handler handler, void* instance);


typedef char* (*yet_value_serializer)(const void* from, char* to);

extern char* yet_serialize_void(const void* from, char* to);
extern char* yet_serialize_sc_integer(const void* from, char* to);
extern char* yet_serialize_sc_real(const void* from, char* to);
extern char* yet_serialize_sc_boolean(const void* from, char* to);
extern char* yet_serialize_sc_string(const void* from, char* to);

#ifdef __cplusplus
}
#endif

#endif
