/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef TICTOCMETA_H_
#define TICTOCMETA_H_

#include <string>

extern std::string TictocMetaFeatureNames[];
extern std::string TictocMetaStateNames[];

#endif /* TICTOCMETA_H_ */
