"""Implementation of statechart light_switch.
Generated by itemis CREATE code generator.
"""

import queue
from yakindu.rx import Observable

class LightSwitch:
	"""Implementation of the state machine LightSwitch.
	"""

	class State:
		""" State Enum
		"""
		(
			main_region_off,
			main_region_on,
			null_state
		) = range(3)
	
	
	class User:
		"""Implementation of scope User.
		"""
		
		def __init__(self, statemachine):
			self.on_button = None
			self.off_button = None
			
			self.statemachine = statemachine
		
		def raise_on_button(self):
			"""Raise method for event on_button.
			"""
			self.statemachine.in_event_queue.put(self.__raise_on_button_call)
			self.statemachine.run_cycle()
		
		def __raise_on_button_call(self):
			"""Raise callback for event on_button.
			"""
			self.on_button = True
		
		def raise_off_button(self):
			"""Raise method for event off_button.
			"""
			self.statemachine.in_event_queue.put(self.__raise_off_button_call)
			self.statemachine.run_cycle()
		
		def __raise_off_button_call(self):
			"""Raise callback for event off_button.
			"""
			self.off_button = True
		
	
	class Light:
		"""Implementation of scope Light.
		"""
		
		def __init__(self, statemachine):
			self.brightness = None
			self.on = None
			self.on_observable = Observable()
			self.off = None
			self.off_observable = Observable()
			
			self.statemachine = statemachine
		
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		self.user = LightSwitch.User(self)
		self.light = LightSwitch.Light(self)
		
		self.in_event_queue = queue.Queue()
		# enumeration of all states:
		self.__State = LightSwitch.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 1
		for __state_index in range(1):
			self.__state_vector[__state_index] = self.State.null_state
		
		# for timed statechart:
		self.timer_service = None
		self.__time_events = [None] * 1
		
		# initializations:
		#Default init sequence for statechart LightSwitch
		self.light.brightness = 0
		self.__is_executing = False
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.main_region_off:
			return self.__state_vector[0] == self.__State.main_region_off
		if s == self.__State.main_region_on:
			return self.__state_vector[0] == self.__State.main_region_on
		return False
		
	def time_elapsed(self, event_id):
		"""Add time events to in event queue
		"""
		if event_id in range(1):
			self.in_event_queue.put(lambda: self.raise_time_event(event_id))
			self.run_cycle()
	
	def raise_time_event(self, event_id):
		"""Raise timed events using the event_id.
		"""
		self.__time_events[event_id] = True
	
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	def __entry_action_main_region_off(self):
		"""Entry action for state 'Off'..
		"""
		#Entry action for state 'Off'.
		self.light.brightness = 0
		self.light.off_observable.next()
		
	def __entry_action_main_region_on(self):
		"""Entry action for state 'On'..
		"""
		#Entry action for state 'On'.
		self.timer_service.set_timer(self, 0, (30 * 1000), False)
		self.light.on_observable.next()
		
	def __exit_action_main_region_on(self):
		"""Exit action for state 'On'..
		"""
		#Exit action for state 'On'.
		self.timer_service.unset_timer(self, 0)
		
	def __enter_sequence_main_region_off_default(self):
		"""'default' enter sequence for state Off.
		"""
		#'default' enter sequence for state Off
		self.__entry_action_main_region_off()
		self.__state_vector[0] = self.State.main_region_off
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_on_default(self):
		"""'default' enter sequence for state On.
		"""
		#'default' enter sequence for state On
		self.__entry_action_main_region_on()
		self.__state_vector[0] = self.State.main_region_on
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_default(self):
		"""'default' enter sequence for region main region.
		"""
		#'default' enter sequence for region main region
		self.__react_main_region__entry_default()
		
	def __exit_sequence_main_region_off(self):
		"""Default exit sequence for state Off.
		"""
		#Default exit sequence for state Off
		self.__state_vector[0] = self.State.null_state
		
	def __exit_sequence_main_region_on(self):
		"""Default exit sequence for state On.
		"""
		#Default exit sequence for state On
		self.__state_vector[0] = self.State.null_state
		self.__exit_action_main_region_on()
		
	def __exit_sequence_main_region(self):
		"""Default exit sequence for region main region.
		"""
		#Default exit sequence for region main region
		state = self.__state_vector[0]
		if state == self.State.main_region_off:
			self.__exit_sequence_main_region_off()
		elif state == self.State.main_region_on:
			self.__exit_sequence_main_region_on()
		
	def __react_main_region__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_off_default()
		
	def __react(self, transitioned_before):
		"""Implementation of __react function.
		"""
		#State machine reactions.
		return transitioned_before
	
	
	def __main_region_off_react(self, transitioned_before):
		"""Implementation of __main_region_off_react function.
		"""
		#The reactions of state Off.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.user.on_button:
				self.__exit_sequence_main_region_off()
				self.light.brightness = 1
				self.__enter_sequence_main_region_on_default()
				self.__react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __main_region_on_react(self, transitioned_before):
		"""Implementation of __main_region_on_react function.
		"""
		#The reactions of state On.
		transitioned_after = transitioned_before
		if transitioned_after < 0:
			if self.user.off_button or self.__time_events[0]:
				self.__exit_sequence_main_region_on()
				self.__time_events[0] = False
				self.__enter_sequence_main_region_off_default()
				self.__react(0)
				transitioned_after = 0
		#If no transition was taken
		if transitioned_after == transitioned_before:
			#then execute local reactions.
			if (self.user.on_button) and (self.light.brightness < 10):
				self.light.brightness = self.light.brightness + 1
			transitioned_after = self.__react(transitioned_before)
		return transitioned_after
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.user.on_button = False
		self.user.off_button = False
		self.__time_events[0] = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		state = self.__state_vector[0]
		if state == self.State.main_region_off:
			self.__main_region_off_react(-1)
		elif state == self.State.main_region_on:
			self.__main_region_on_react(-1)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__micro_step()
			self.__clear_in_events()
			condition_0 = False
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
				condition_0 = True
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.timer_service is None:
			raise ValueError('Timer service must be set.')
		
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart LightSwitch
		self.__enter_sequence_main_region_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart LightSwitch
		self.__exit_sequence_main_region()
		self.__is_executing = False
	
	
	def trigger_without_event(self):
		"""Implementation of triggerWithoutEvent function.
		"""
		self.run_cycle()
	
