/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.sct.examples.codegen.java.lightswitch;

import org.yakindu.sct.examples.codegen.java.IStatemachine;

public interface ILightSwitchStatemachine extends IStatemachine {
	public interface SCIUser {
	
		public void raiseOn_button();
		
		public void raiseOff_button();
		
		public long getBrightness();
		
		public void setBrightness(long value);
		
	}
	
	public SCIUser getSCIUser();
	
}
