/** Generated by YAKINDU Statechart Tools code generator. */
package org.yakindu.sct.examples.codegen.java;

import org.yakindu.sct.IStatemachine;

public interface ILightSwitch extends IStatemachine {
	
	public interface InterfaceUser {
	
		public void raiseOn_button();
		
		public void raiseOff_button();
		
		public long getBrightness();
		
		public void setBrightness(long value);
		
	}
	
	public InterfaceUser getInterfaceUser();
	
}
