/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef SC_TRACING_H_
#define SC_TRACING_H_


#include "sc_types.h"

namespace sc {
namespace tracing {

/*! Enumeration of all trace event types */
typedef enum
{
	machine_enter,
	machine_exit,
	machine_run_cycle_start,
	machine_run_cycle_end,
	state_entered,
	state_exited,
	event_raised,
	variable_set,
	time_event_raised,
	time_event_set,
	time_event_unset
} TraceEventType;


class TraceEvent {
	public:
		TraceEvent(TraceEventType type, void* source, sc_integer id, const void* value) :
			type(type), source(source), elementId(id), value(value) {}

		virtual ~TraceEvent() {}

		TraceEventType type;
		void* source;
		sc_integer elementId;
		const void* value;
};


} // namespace tracing
} // namespace sc


#endif /* SC_TRACING_H_ */
