/** Generated by YAKINDU Statechart Tools code generator. */


#ifndef TICTOCTRACER_H_
#define TICTOCTRACER_H_


#include "base/yet_sc_tracer.h"


#include "Tictoc.h"
#include "TictocMeta.h"


#ifdef __cplusplus
extern "C"
{
#endif


extern void tictoc_init_sc_tracer(yet_sc_tracer *tracer, Tictoc* machine);


#ifdef __cplusplus
}
#endif


#endif /* TICTOCTRACER_H_ */
