/** Generated by YAKINDU Statechart Tools code generator. */

#include "TictocMeta.h"				
		
sc_string TictocMeta_feature_names[] = {
	"<nothing>",
	"toggle",
	"tic",
	"toc",
	"count",
	"delay",
	"x",
	"b",
	"y",
	"i"
};

sc_string TictocMeta_state_names[] = {
	"<nostate>",
	"main.Idle",
	"main.Playing",
	"main.Playing.active.Tic",
	"main.Playing.active.Toc"
};
