/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef TICTOCMETA_H_
#define TICTOCMETA_H_

#include "base/sc_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern sc_string TictocMeta_feature_names[];

extern sc_string TictocMeta_state_names[];

#ifdef __cplusplus
}
#endif

#endif /* TICTOCMETA_H_ */
