/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef TIMEDSTATEMACHINEINTERFACE_H_
#define TIMEDSTATEMACHINEINTERFACE_H_

#include "sc_types.h"
#include "TimerInterface.h"

/*! \file Interface for state machines which use timed event triggers.
*/
class TimedStatemachineInterface {
	public:
	
		virtual ~TimedStatemachineInterface() = 0;
		
		/*! Set the ITimerService for the state machine. It must be set
		    externally on a timed state machine before a run cycle can be correct
		    executed.
		*/
		virtual void setTimer(TimerInterface* timerInterface) = 0;
		
		/*! Returns the currently used timer service.
		*/
		virtual TimerInterface* getTimer() = 0;
		
		/*! Callback method if a time event occurred.
		*/
		virtual void raiseTimeEvent(sc_eventid event) = 0;
		
		/*! Method to retrieve the number of time events that can be 
			active at once in this state machine.
		*/
		virtual sc_integer getNumberOfParallelTimeEvents() = 0;
};

inline TimedStatemachineInterface::~TimedStatemachineInterface() {}

#endif /* TIMEDSTATEMACHINEINTERFACE_H_ */
